### ISSUE TITLE
Validation failure with default values of type integer or boolean

### ISSUE THREAD

**Issue by jnflint** [go-openapi/validate#105]
Getting validation failures for spec https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.json

Errors are:

> default value for page in query does not validate its schema
page in query must be of type integer: "string"
default value for page-size in query does not validate its schema
page-size in query must be of type integer: "string"
in operation "getAccountDetail", default value in response 200 does not validate its schema
200.data.allOf[0].isOwned.default in body must be of type boolean: "string"
in operation "listAccounts", default value in response 200 does not validate its schema
200.data.accounts.items.default.isOwned.default in body must be of type boolean: "string"
definitions.Account.isOwned.default in body must be of type boolean: "string"

What I think are the relevant sections of the spec:

```json
 "ParamPage": {
      "name": "page",
      "in": "query",
      "description": "Page of results to request (standard pagination)",
      "required": false,
      "type": "integer",
      "default": "1"
    },
 "ParamPageSize": {
      "name": "page-size",
      "in": "query",
      "description": "Page size to request. Default is 25 (standard pagination)",
      "required": false,
      "type": "integer",
      "default": "25"
 }
"isOwned": {
       "type": "boolean",
       "description": "Flag indicating that the customer associated with the authorisation is an owner of the account.  Does not indicate sole ownership, however.  If no present then 'true' is assumed",
       "default": "true"
    }
```

Loading the file in editor.swagger.io seems to work fine

**Comment by casualjim** [comment]
then that's a bug in the editor

**Comment by jnflint** [comment]
Ok, that could be so. I don't know enough about the swagger spec to understand what is wrong.
Do you mind helping me out and letting me know how 
```json
 "ParamPage": {
      "name": "page",
      "in": "query",
      "description": "Page of results to request (standard pagination)",
      "required": false,
      "type": "integer",
      "default": "1"
    }
```
Can be validly implemented (ie. integer type with default value) in a swagger spec?

Appreciated.

**Comment by casualjim** [comment]
```json
 "ParamPage": {
      "name": "page",
      "in": "query",
      "description": "Page of results to request (standard pagination)",
      "required": false,
      "type": "integer",
      "default": 1
    }
```

**Comment by jnflint** [comment]
Thanks, I stupidly thought the supplied spec must be valid. Thanks for answering my query. Great library.
