### ISSUE TITLE
extra rules validations for openapi 3.0.X version

### ISSUE THREAD

**Issue by RekhaPriya** [go-openapi/validate#111]
Hi, 
Can you please confirm if this package doing the [extra validations](https://godoc.org/github.com/go-openapi/validate#hdr-Validating_a_specification) for openapi 3.0 version as well ?

Also I just want to use this package only for extra rule validation, as I have a written a separate program to do the swagger2.0/json schema validation. Is that possible ?

**Comment by fredbi** [comment]
@RekhaPriya this package does not support OpenApi 3.0. Only 2.0.

**Comment by RekhaPriya** [comment]
@fredbi Hi, Any plan in future to support OpenApi 3.0 ?

**Comment by RekhaPriya** [comment]
@fredbi Can you please consider the OpenApi3.0 support as a feature request/enhancement ? Thanks!
