### ISSUE TITLE
New errors validating a file without a .yaml extension

### ISSUE THREAD

**Issue by bytheway** [go-openapi/validate#135]
We've been using the go-openapi project for a while to help run some sanity check style validations on our documents. We have some extension properties in our documents (for GCP endpoint security) which never caused an issue with validations before, but after updating some dependencies we now get errors like:

```
	could not resolve reference in /bravo-api to $ref : invalid character 'x' looking for beginning of value
	could not resolve reference in /bravo-api/healthN to $ref : invalid character 'x' looking for beginning of value
	could not resolve reference in /bravo-api/internal/heartbeat to $ref : invalid character 'x' looking for beginning of value
```

Here are the versions we have in go.mod when not working

```
	github.com/go-openapi/analysis v0.19.16
	github.com/go-openapi/loads v0.20.0
	github.com/go-openapi/spec v0.20.0
	github.com/go-openapi/strfmt v0.19.11
	github.com/go-openapi/validate v0.20.0
```

Running against the older version validates without issue:

```
	github.com/go-openapi/analysis v0.19.7
	github.com/go-openapi/errors v0.19.3 // indirect
	github.com/go-openapi/loads v0.19.4
	github.com/go-openapi/runtime v0.19.10 // indirect
	github.com/go-openapi/spec v0.19.5
	github.com/go-openapi/strfmt v0.19.4
	github.com/go-openapi/swag v0.19.7 // indirect
	github.com/go-openapi/validate v0.19.6
```

**Comment by fredbi** [comment]
Interesting.
Could you please share the swagger spec document that caused this issue?

**Comment by fredbi** [comment]
Is your document a yaml doc?

This looks to me like the latest change to "go-openapi/loads" could be the culprit. This error looks very much like some internal document fetcher no more fetches yaml docs but only json docs. Just a hunch

**Comment by bytheway** [comment]
the document is yaml. I put a subset of our code (ugly as it is) in a repo which does reproduce the error.

https://github.com/bytheway/openapi-testcase

In our case we have some variables that we have in our raw openapi files that are substituted with some simple string replacements. In putting the repo together I noticed that the validation passes if I load the `valid.yaml` file directly, but is failing when written to a tempfile and then validated.  Might give some clues as to what is going on.

**Comment by bytheway** [comment]
I was able to get this working in my project by changing my tempfile name to have a .yaml file extension. It seems that whatever recent change was made doesn't properly detect that the file is yaml if the file doesn't have an extension. 

```
ioutil.TempFile("", "openapi")
```

to

```
ioutil.TempFile("", "openapi*.yaml")
```

**Comment by fredbi** [comment]
@bytheway  ok I could reproduce your issue.
I think that your code used to rely on some package level persistence of cached $ref. It should never have worked,
but because of this undue "memory", it worked.

The actual issue with your program is that the new file has no yaml extension, so the loader tries it as json.

If you change your "munged" file name to `mungedFile, err := ioutil.TempFile("", "openapi.*.yaml")` everything works as expected.

**Comment by bytheway** [comment]
Yeah, looks like we came to the same conclusion.  👍 Thanks for the help!
