### ISSUE TITLE
Validation extremely slow

### ISSUE THREAD

**Issue by nikgalushko** [go-openapi/validate#146]
Hi. I used the project long time and it's a fantastic product. I recently upgrade github.com/go-openapi/validate in my project from v0.19.7 to v0.20.3 and the validation speed has dropped dramatically.
My current specification is really huge ~16000 lines and v0.19.7 validates it about 7-8 seconds but v0.20.3 takes 7-8 minutes.

**Comment by nikgalushko** [comment]
If it's helpful I can send a CPU profile from my benchmark.

**Comment by kzys** [comment]
@nikgalushko That would definitely help our investigation.

**Comment by casualjim** [comment]
Interesting, in this repo the changes seem really benign. It would be good to know some more about the specification file too. Maybe it's not possible to share the spec but can is it possible that there are a lot of `$ref` objects in there and is there $ref recursion?

**Comment by vitkarpenko** [comment]
Hi! I've encountered the same problem while updating `go-openapi/validate` from 0.19.7 to 0.21.0 with the same specification file as nikgalushko. For me validation time also jumped from ~4s on 0.19.7 to almost 6 minutes on the latest version.

@casualjim, our spec is indeed contains a lot of refs (2100+), not sure about recursion though, I'll check it.

I'm attaching CPU profiles for both versions. Take a look please :)

[validate_pprof.zip](https://github.com/go-openapi/validate/files/8463812/validate_pprof.zip)

**Comment by vitkarpenko** [comment]
There are some $ref recursions too.

**Comment by vitkarpenko** [comment]
Using expanded analyzer actually fixed the issue. Thank you, @koron.
