### ISSUE TITLE
Why is mongo-driver a dependency of go-openapi/validate

### ISSUE THREAD

**Issue by sordina** [go-openapi/validate#185]
Seems weird. Feel free to close this if I'm missing something!

![image](https://github.com/go-openapi/validate/assets/92299/3e0dd3ee-e259-4bce-b145-eb378e040acd)

**Comment by fredbi** [comment]
@sordina yes this is a bit unfortunate, but that’s valid:
Validate builds on top of go-openapi/strfmt.
The types exposed by this package support BSON marshaling, hence the dependency (unused here)

**Comment by sordina** [comment]
Makes sense. It's a shame there's not a more granular dependency available for the BSON marshalling. I'll see if mongo-driver has any possibility of exposing this separately.
