### ISSUE TITLE
Standalone validation of http.Request objects

### ISSUE THREAD

**Issue by igorsechyn** [go-openapi/validate#24]
Hi,

I am currently investigating the idea of writing a simple middleware for validating http requests and responses against a swagger spec in a proxy server. I.e. I do not want to use the whole middleware and router implementation provided by go-openapi.

I was wondering, if there is an example for that or if it is possible in general?

Cheers, Igor.

**Comment by casualjim** [comment]
The code is there but some methods are not exported.

https://github.com/go-openapi/runtime/blob/master/middleware/request.go
It does require you to create a context and get to a matched route https://github.com/go-openapi/runtime/blob/master/middleware/router.go#L145-L167

The router is more to find one of those matched routes based on the request. From there on you can use that to validate a request. 

hope this helps.

**Comment by igorsechyn** [comment]
Thanks for a quick response. I ended up creating a context object with a custom RoutedApi, which returns the same handler for each path/operation combination, proxying it to the target
