### ISSUE TITLE
Is there any documentation/tutorial?

### ISSUE THREAD

**Issue by nikhita** [go-openapi/validate#25]
I could not find any tutorial or examples on how to use this package (maybe I missed it). Please let me know if there are some simple examples mentioned anywhere. Thanks.

**Comment by casualjim** [comment]
What is it you're trying to achieve? validate a spec or validate data against a spec?

**Comment by nikhita** [comment]
Thanks for the quick reply, validate data against a spec.

**Comment by casualjim** [comment]
if you have a swagger spec you can get the schema you want to validate against by getting it from the definitions
Then you can call this function: https://github.com/go-openapi/validate/blob/master/spec.go#L60

Let's say I have a defintion called User, you'd get something that looks like this:

```go
var model models.User
json.Unmarshal(bytes, &model)

var spec *spec.Swagger = getSpec()
schema := spec.Definitions["User"]

if err := validate.AgainstSchema(schema, &model, strfmt.Default); err != nil {
  return err
}
```

**Comment by nikhita** [comment]
Thanks a lot for your response and sorry for the noob question but is it possible to validate an instance of a schema against the (openapi) schema without the openapi spec around it?

**Comment by casualjim** [comment]
I'm confused about this question :)

You want to validate a swagger spec (schema in your question) against the openapi specification to see if the spec is valid? Or do you want to validate a datastructure against a schema in the definitions of the swagger spec?

**Comment by nikhita** [comment]
Sorry I wasn't clear before.

I have a JSON payload (request or response body) and I have a schema to validate it against. Is it possible to achieve this validation? :)

**Comment by nikhita** [comment]
Gah, I saw your answer on SO. I was confused and got it cleared now! Thanks a lot!

**Comment by nikhita** [comment]
Also, I really appreciate you helping out so well. It's very hard to find maintainers who do that. :)
Thanks again, closing the issue.

**Comment by cam-hashemi** [comment]
I don't think the original question was really answered.

Is there any documentation on this project outside of issues and stackoverflow?

**Comment by fredbi** [comment]
There is this, with some examples for usage: https://godoc.org/github.com/go-openapi/validate

**Comment by cam-hashemi** [comment]
thank you @fredbi 👍

**Comment by SahilAgrawal-Druva** [comment]
@nikhita while I was skimming around, found this thread.
Did you face issue when validating an embedded struct in Body against schema?
