### ISSUE TITLE
validation issue: can't have same parameter name in path and formData

### ISSUE THREAD

**Issue by weching** [go-openapi/validate#3]
If the name of path parameter and form parameter is same, then validation failed. Definition, eg:

```
"parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "formData",
            "description": "",
            "required": false,
            "type": "string"
          }
        ]
```

Error:
> path param \"{id}\" has no parameter definition

As per swagger spec, the definition is allowed.

**Comment by vburenin** [comment]
Interesting. It seems like it might also affect query string as well. It seem like all parameters need to be separated into different groups such as query params, form param and path params and combined into one struct using composition.

So, it Go will produce efficient code and data structures meanwhile fighting ambiguous definitions.

Something like it: https://play.golang.org/p/JNKcPIy8JL

**Comment by casualjim** [comment]
fwiw this is just for validation, code generation is not a goal/consideration for this particular component 

I think the analyzer needs to be able to generate another view of params that's not a single bag.
https://github.com/go-openapi/analysis/blob/master/analyzer.go#sourcegraph&def=GoPackage/github.com/go-openapi/analysis/-/Spec/ParamsFor&L444-451

And then the validation needs to take that into account here: 
https://github.com/go-openapi/validate/blob/master/spec.go#L512
which in turn ends up here
https://github.com/go-openapi/validate/blob/master/spec.go#L358

**Comment by weching** [comment]
@vburenin As per the testing, only for path + form param. All other combinations are fine.

**Comment by vburenin** [comment]
@weching Thank you, I will look into it deeper when I have enough time for open source fun.
