### ISSUE TITLE
compile error when trying to include github.com/go-openapi/analysis

### ISSUE THREAD

**Issue by pitiwari** [go-openapi/validate#82]
I am trying to use openapi to validate crd schema. I used  glide to install the opeapi but i am getting compilation error below while trying to compile

code:

package validate

import (
"github.com/go-openapi/analysis"
)

error:

GOROOT=/usr/local/go #gosetup
GOPATH=/Users/pitiwari/go-ws #gosetup
/usr/local/go/bin/go build -i -o /private/var/folders/y4/zplxn82n5293wh__31pqxsth39682s/T/___go_build_crd_validator_go /Users/pitiwari/go-ws/src/github.com/ebayinc/ingress/crd_validator.go #gosetup
# github.com/ebayinc/ingress/vendor/github.com/go-openapi/strfmt
vendor/github.com/go-openapi/strfmt/format.go:96:9: cannot use func literal (type func(reflect.Type, reflect.Type, interface {}) (interface {}, error)) as type mapstructure.DecodeHookFunc in return argument

Compilation finished with exit code 2

**Comment by fredbi** [comment]
go-openapi repos now tagged since 0.15. So dep gets the constraint on the version for all go-openapi repos
