### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by bah2830** [go-openapi/validate#99]
In the latest master (commit 4f81262a03dbefe1003f745d3d0a03cbeea98d50) I am getting

```
vendor/github.com/go-openapi/validate/helpers.go:188:9: undefined: spec.ExpandParameterWithRoot
vendor/github.com/go-openapi/validate/helpers.go:241:9: undefined: spec.ExpandResponseWithRoot
```

this was not happening on 0.15.0 so I have a workaround for now but figured I'd bring the issue up.

It looks like the issue may have come from https://github.com/go-openapi/validate/pull/98. The CI bot found the issue but it was still merged.

**Comment by fredbi** [comment]
When you build from master, you have to get your dependencies from master as well.
In your case, you upgraded validate, but not the dependency on spec?

**Comment by casualjim** [comment]
we tag releases together. So if you depend on 0.15.0 for go-swagger/go-swagger dep should pull in the 0.15.0 tags of the go-openapi repos

We won't add dependency management in the libraries. We make sure HEAD master branches all work together

**Comment by gregmarr** [comment]
This tagging is new, so 0.15.0 is the first version where all the `go-openapi` repos have a tag that matches the `go-swagger` release.

**Comment by pprasadk** [comment]
I am also facing the same problem. Please suggest the fix.

**Comment by fredbi** [comment]
dep ensure -update

**Comment by fredbi** [comment]
Now all go-openapi and go-swagger repos have moved to go modules to manage dependencies.
This may be safely closed, I'd reckon.
